### signup user
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "luffy",
    "email": "luffy@acme.org",
    "password": "hunter42"
}

### signin user (valid)

# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "luffy@acme.org",
    "password": "hunter42"
}

@token = {{signin.response.body.token}}

### signin user (invalid)
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "luffy@acme.org",
    "password": "invalidpwd"
}

### chat api
GET http://localhost:6688/api/chat
Authorization: Bearer {{token}}
