### signup user1
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "onepiece",
    "fullname": "luffy",
    "email": "luffy@acme.org",
    "password": "hunter42"
}

### signup user2
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "onepiece",
    "fullname": "zoro",
    "email": "zoro@acme.org",
    "password": "hunter42"
}

### signin user (invalid)
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "luffy@acme.org",
    "password": "invalidpwd"
}

### signin user (valid)
# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "luffy@acme.org",
    "password": "hunter42"
}

@token = {{signin.response.body.token}}

### get user list
GET http://localhost:6688/api/users
Authorization: Bearer {{token}}

### get chat list
GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}

### create chat
POST  http://localhost:6688/api/chats
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "learning rust",
    "members": [1, 2],
    "public": false
}

### get chat by id
GET http://localhost:6688/api/chats/5
Authorization: Bearer {{token}}

### update chat
PATCH  http://localhost:6688/api/chats/5
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "learning rust",
    "members": [1, 2],
    "public": true
}

### update chat
DELETE  http://localhost:6688/api/chats/5
Authorization: Bearer {{token}}
Content-Type: application/json
